### PR TITLE
Add markdown README and update with some additional context

### PR DESCRIPTION
**Pull request by eigenbeam**
Here's a markdown version of the README that also includes a little more context for getting started with the project as a developer. I pulled a simple README template from some site and populated it with what I thought would be helpful, largely pulling from the existing .rst file. Do we want to keep the README as .rst or should we move to .md? I can update this PR either way.

### CODE REVIEW

**Comment by juliacollins** [comment]
Unless there's an advantage to `.rst` I'd prefer `.md`. But perhaps Python projects lean towards `.rst`? I don't know why I did this, but I created a completely new branch for my experiments in the `forge-py` repo rather than commit to `develop`. Perhaps because I'm guessing we'll need to do enough of a re-write that it would be better treated as an entirely new code base. I'm fine with mods to `develop` here since they might be the kind of thing you can hand back to PO.DAAC.

**Review by juliacollins — APPROVED** [review]
I appreciate the step-by-step!

**Comment by eigenbeam** [comment]
I prefer the .md too. Should I remove the .rst?

Should I make a `main` branch and merge these changes to it instead of `develop`?

**Comment by juliacollins** [comment]
> I prefer the .md too. Should I remove the .rst?
> 
> Should I make a `main` branch and merge these changes to it instead of `develop`?

I'm trying to not overthink this. :-) The changes so far are ones that would be useful to contribute back, so let's stick with `develop` for now. Unless you feel strongly about a different approach. :-)

**Comment by eigenbeam** [comment]
I'm going to leave the RST in place for now, but let me know if we should go ahead and remove it. My thought was if PODAAC makes changes we want to include we could pull down their changes to their RST and incorporate into our README, avoiding some messiness, maybe.

**Pull request merged**
